services:
  - type: web
    name: specific-spring-backend
    env: docker
    plan: free
    rootDir: .
    dockerCommand: /app/startup.sh
    healthCheckPath: /health
    envVars:
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
      - key: DEEPL_API_KEY
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080

databases:
  - name: specific-db
    plan: free
    databaseName: specific
    user: specific 