services:
  - type: web
    name: specific-spring-backend
    env: docker
    plan: free
    rootDir: .
    dockerCommand: java -Dspring.profiles.active=prod -jar /app/app.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: specific-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: specific-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: specific-db
          property: password
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
      - key: DEEPL_API_KEY
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: specific-db
    plan: free
    databaseName: specific
    user: specific 