services:
  - type: web
    name: specific-spring-backend
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_PASSWORD
        sync: false
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
      - key: DEEPL_API_KEY
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080 