services:
  - type: web
    name: specific-spring-backend
    env: docker
    plan: free
    healthCheckPath: /health
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: DATABASE_PASSWORD
        value: SpecificPostgre
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
      - key: DEEPL_API_KEY
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: JAVA_OPTS
        value: "-XX:MaxRAM=512m -XX:+UseSerialGC -Xss512k -Dspring.datasource.hikari.maximumPoolSize=3" 